### ISSUE TITLE
Do you any algorithm in Lua?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/lua#1]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Lua](https://github.com/AllAlgorithms/lua) this case

**Comment by elisauhura** [comment]
I'm implementing a few algorithms here for this repo. I may send a PR in the weekend.

Intended algorithms:
- Bubble Sort
- Selection Sort
- Merge Sort (alternative implementation)
- Quick Sort
- Range Sum
